CREATE TABLE CURSO (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOMBRE          VARCHAR2(150)  NOT NULL,
    DESCRIPCION     VARCHAR2(500),
    INSTRUCTOR      VARCHAR2(150),
    CUPOS           NUMBER(10),
    VALOR           NUMBER(12,2),
    S3_KEY          VARCHAR2(250)
);

COMMENT ON TABLE  CURSO               IS 'Cursos de la plataforma, gestionados por el instructor';
COMMENT ON COLUMN CURSO.ID            IS 'Identificador unico del curso (autogenerado)';
COMMENT ON COLUMN CURSO.NOMBRE        IS 'Nombre del curso';
COMMENT ON COLUMN CURSO.DESCRIPCION   IS 'Descripcion del contenido del curso';
COMMENT ON COLUMN CURSO.INSTRUCTOR    IS 'Nombre del instructor que gestiona el curso';
COMMENT ON COLUMN CURSO.CUPOS         IS 'Cantidad de cupos disponibles';
COMMENT ON COLUMN CURSO.VALOR         IS 'Valor o precio del curso';
COMMENT ON COLUMN CURSO.S3_KEY        IS 'Clave del archivo de material almacenado en AWS S3';

CREATE TABLE INSCRIPCION_PROCESADA (
    ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RUT_ESTUDIANTE      VARCHAR2(15)   NOT NULL,
    NOMBRE_ESTUDIANTE   VARCHAR2(150),
    CORREO_ESTUDIANTE   VARCHAR2(150),
    ID_CURSO            NUMBER(19),
    NOMBRE_CURSO        VARCHAR2(150),
    FECHA_INSCRIPCION   TIMESTAMP
);

COMMENT ON TABLE  INSCRIPCION_PROCESADA                    IS 'Inscripciones procesadas desde la cola principal y guardadas en Oracle';
COMMENT ON COLUMN INSCRIPCION_PROCESADA.ID                 IS 'Identificador unico de la inscripcion (autogenerado)';
COMMENT ON COLUMN INSCRIPCION_PROCESADA.RUT_ESTUDIANTE     IS 'RUT del estudiante inscrito';
COMMENT ON COLUMN INSCRIPCION_PROCESADA.NOMBRE_ESTUDIANTE  IS 'Nombre del estudiante';
COMMENT ON COLUMN INSCRIPCION_PROCESADA.CORREO_ESTUDIANTE  IS 'Correo del estudiante';
COMMENT ON COLUMN INSCRIPCION_PROCESADA.ID_CURSO           IS 'Identificador del curso al que se inscribe';
COMMENT ON COLUMN INSCRIPCION_PROCESADA.NOMBRE_CURSO       IS 'Nombre del curso al que se inscribe';
COMMENT ON COLUMN INSCRIPCION_PROCESADA.FECHA_INSCRIPCION  IS 'Fecha y hora en que se proceso la inscripcion';

INSERT INTO CURSO (NOMBRE, DESCRIPCION, INSTRUCTOR, CUPOS, VALOR)
VALUES ('Desarrollo Cloud Native', 'Curso de arquitecturas en la nube con Spring Boot', 'Nicole Plaza', 30, 250000);

INSERT INTO CURSO (NOMBRE, DESCRIPCION, INSTRUCTOR, CUPOS, VALOR)
VALUES ('Introduccion a DevOps', 'Fundamentos de integracion y despliegue continuo', 'Nicole Plaza', 25, 200000);

COMMIT;