server.port=8080

# Base de datos Oracle (AWS RDS)
spring.datasource.url=jdbc:oracle:thin:@//TU_ENDPOINT_RDS:1521/ORCL
spring.datasource.username=admin
spring.datasource.password=PASSWORD
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# AWS S3
aws.s3-bucket=BUCKET_S3
aws.region=us-east-1

# Seguridad Azure AD B2C
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/TU_TENANT_ID/v2.0

# Azure AD B2C - para el endpoint de autenticacion (BFF)
azure.tenant-id=${AZURE_TENANT_ID:823b12b4-9c38-436c-b51a-1af729219b7f}
azure.client-id=${AZURE_CLIENT_ID:48a39aae-b7c4-4972-a77c-fefd35eba069}
azure.client-secret=${AZURE_CLIENT_SECRET}
azure.scope=${AZURE_SCOPE:https://duocazure20.onmicrosoft.com/48a39aae-b7c4-4972-a77c-fefd35eba069/.default}
